language: c

addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - yasm
      - check
      - libdbus-1-dev
      - libopenal-dev
      - libopenal-data
      - libopenal1
      - libv4l-dev

cache:
  directories:
    - $HOME/cache

jobs:
  fast_finish: true
  include:
    - name: "Linux Clang"
      os: linux
      env: BUILD=linux
      compiler: clang

    - name: "Windows x64"
      os: linux
      env: BUILD=windows
      compiler: x86_64-w64-mingw32-gcc
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc
            - mingw-w64
            - gcc-mingw-w64
            - mingw-w64-common
            - binutils-mingw-w64
            - yasm
            - libopenal-dev
            - libopenal-data
            - libopenal1

    - os: osx
      compiler: clang
      env: BUILD=osx

git:
  depth: 5

before_script:
  - ./extra/travis/env.sh
  - ./extra/travis/${BUILD}-before.sh
  - ./extra/travis/filter_audio.sh

script:
  - ./extra/travis/${BUILD}-script.sh

after_failure:
  - ./extra/travis/debug_failure.sh

deploy:
  provider: releases
  edge: true
  token:
    secure: gJ2KB3TFriIMUub9kJJuP52BiOC62S4iHmlszer9L/2E7pF7v+lvDHSXm9/W73ZDh9P1xUu8Vah3NmvHCQiCMaJP5R3jRC4gEPcGIv8yuk84O5VpaOxj6I1kbvLjqRHShAhEC1GdzCyITJvM3EhLQb9FyHv7Kn7VWbJDVDK7bg4k1ZhNrIjwnUNpYNlqwfAgLir1lfjVE5jXViimiwOGpSqpUMSRyGKCB1TMenSdaPQD7oTI7ijp0YyPpCsJBlV81Zp38rPSpELwSabmRhPXBVhXha1dh9lxQDPTI0Z3K3KiG28DFyv7JfWZfBySRJBDrVV+QPfmyjov8dCUu0A3lGXF7XFhXY5mYzmfkFoYtYw85LwoS11wKmdTyUMQ57FqYUjVfbrT9K+DRSXvMddHruM5B9IyvYYW0DlW18PH7m3NqR+arT5/Z1GhK1+zg8adJdngHfwTtZ+/Wh7pmSJkPaZOQ695THWh2I/URJcmUWXdDea/9OcLfo/gkFH+9Nia7KLyeJUISFku1iRWPwwik++olSpRA0fNmVAraaNZrBvSS2EdzMIeN/vi82y7BujgR4Eb2QW6TNMdJl5K3QupL8DVSn5C+rqaytf7B9i4LEG741/3ZSsIFWnBZak29SBwCKL0G/wlEWAKGOi06prIWn7eFtRuI/dTj8vouDRL3BQ=
  file: ./build_win/utox.exe
  on:
    tags: true
    condition: $BUILD = windows

branches:
  except:
